-- MySQL Script generated by MySQL Workbench
-- 08/30/16 16:33:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nettick
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nettick
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nettick` DEFAULT CHARACTER SET utf8 ;
USE `nettick` ;

-- -----------------------------------------------------
-- Table `nettick`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `fechaSolicitud` DATE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `hora_visita` DATE NULL,
  `nombre_contacto` VARCHAR(30) NOT NULL,
  `apellido_contacto` VARCHAR(30) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `telefono_contacto` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `prioridad` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitud_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_solicitud_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `nettick`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `prioridad` VARCHAR(45) NULL,
  `fechaIngreso` DATE NOT NULL,
  `fechaModificacion` VARCHAR(45) NULL,
  `piso` VARCHAR(20) NULL,
  `sector` VARCHAR(30) NULL,
  `solicitud_idsolicitud` INT NOT NULL,
  `observacionInicial` VARCHAR(400) NULL,
  `observacionFinal` VARCHAR(400) NULL,
  `compromisos` VARCHAR(400) NULL,
  PRIMARY KEY (`idProyecto`),
  INDEX `fk_requerimiento_solicitud1_idx` (`solicitud_idsolicitud` ASC),
  CONSTRAINT `fk_requerimiento_solicitud1`
    FOREIGN KEY (`solicitud_idsolicitud`)
    REFERENCES `nettick`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`cubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`cubicacion` (
  `idCubicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `fecha_modificacion` DATE NULL,
  `fecha_envio` DATE NULL,
  `fecha_aprovacion` DATE NULL,
  `Estado_idEstado` INT NOT NULL,
  `proyecto_idProyecto` INT NOT NULL,
  PRIMARY KEY (`idCubicacion`),
  INDEX `fk_Cubicacion_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Cubicacion_proyecto1_idx` (`proyecto_idProyecto` ASC),
  CONSTRAINT `fk_Cubicacion_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `nettick`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cubicacion_proyecto1`
    FOREIGN KEY (`proyecto_idProyecto`)
    REFERENCES `nettick`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`rubro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`rubro` (
  `idRubro` INT NOT NULL AUTO_INCREMENT,
  `nombre_rubro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRubro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`actividad_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`actividad_categoria` (
  `idActividad_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `Rubro_idRubro` INT NOT NULL,
  PRIMARY KEY (`idActividad_categoria`),
  INDEX `fk_actividad_categoria_Rubro1_idx` (`Rubro_idRubro` ASC),
  CONSTRAINT `fk_actividad_categoria_Rubro1`
    FOREIGN KEY (`Rubro_idRubro`)
    REFERENCES `nettick`.`rubro` (`idRubro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`actividad_plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`actividad_plantilla` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre_act` VARCHAR(45) NOT NULL,
  `valor` INT NULL,
  `tiempo_ejecucion` INT NULL,
  `idActividad_categoria` INT NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_actividad_categoria1_idx` (`idActividad_categoria` ASC),
  CONSTRAINT `fk_Actividad_actividad_categoria1`
    FOREIGN KEY (`idActividad_categoria`)
    REFERENCES `nettick`.`actividad_categoria` (`idActividad_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`unidadm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`unidadm` (
  `idunidadM` INT NOT NULL AUTO_INCREMENT,
  `nombre_unidad` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunidadM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre_material` VARCHAR(60) NOT NULL,
  `cod_fabricante` VARCHAR(45) NOT NULL,
  `valor` INT NULL,
  `unidadM_idunidadM` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_Material_unidadM1_idx` (`unidadM_idunidadM` ASC),
  INDEX `fk_Material_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Material_unidadM1`
    FOREIGN KEY (`unidadM_idunidadM`)
    REFERENCES `nettick`.`unidadm` (`idunidadM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `nettick`.`marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`material_has_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`material_has_actividad` (
  `Material_idMaterial` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `cantMaterial` INT NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Material_idMaterial`, `Actividad_idActividad`),
  INDEX `fk_Material_has_Actividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  INDEX `fk_Material_has_Actividad_Material1_idx` (`Material_idMaterial` ASC),
  CONSTRAINT `fk_Material_has_Actividad_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `nettick`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Actividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `nettick`.`actividad_plantilla` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`herramienta_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`herramienta_categoria` (
  `idherramienta_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`idherramienta_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`herramienta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`herramienta` (
  `idHerramienta` INT NOT NULL AUTO_INCREMENT,
  `nombre_herramienta` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `herramienta_categoria_idherramienta_categoria` INT NOT NULL,
  PRIMARY KEY (`idHerramienta`),
  INDEX `fk_Herramienta_herramienta_categoria1_idx` (`herramienta_categoria_idherramienta_categoria` ASC),
  CONSTRAINT `fk_Herramienta_herramienta_categoria1`
    FOREIGN KEY (`herramienta_categoria_idherramienta_categoria`)
    REFERENCES `nettick`.`herramienta_categoria` (`idherramienta_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`herramienta_has_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`herramienta_has_actividad` (
  `Herramienta_idHerramienta` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`Herramienta_idHerramienta`, `Actividad_idActividad`),
  INDEX `fk_Herramienta_has_Actividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  INDEX `fk_Herramienta_has_Actividad_Herramienta1_idx` (`Herramienta_idHerramienta` ASC),
  CONSTRAINT `fk_Herramienta_has_Actividad_Herramienta1`
    FOREIGN KEY (`Herramienta_idHerramienta`)
    REFERENCES `nettick`.`herramienta` (`idHerramienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Herramienta_has_Actividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `nettick`.`actividad_plantilla` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`gama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`gama` (
  `idGama` INT NOT NULL AUTO_INCREMENT,
  `linea_producto` VARCHAR(45) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idGama`),
  INDEX `fk_Gama_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Gama_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `nettick`.`marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombreCargo` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre_trabajador` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(20) NOT NULL,
  `apellidoM` VARCHAR(20) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `observacion` VARCHAR(400) NULL,
  `cargo_idcargo` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtrabajador`),
  INDEX `fk_trabajador_cargo1_idx` (`cargo_idcargo` ASC),
  CONSTRAINT `fk_trabajador_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `nettick`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`proyecto_has_trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`proyecto_has_trabajador` (
  `proyecto_idProyecto` INT NOT NULL,
  `trabajador_idTrabajador` INT NOT NULL,
  `encargado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`proyecto_idProyecto`, `trabajador_idTrabajador`),
  INDEX `fk_requerimiento_has_trabajador_trabajador1_idx` (`trabajador_idTrabajador` ASC),
  INDEX `fk_requerimiento_has_trabajador_requerimiento1_idx` (`proyecto_idProyecto` ASC),
  CONSTRAINT `fk_requerimiento_has_trabajador_requerimiento1`
    FOREIGN KEY (`proyecto_idProyecto`)
    REFERENCES `nettick`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requerimiento_has_trabajador_trabajador1`
    FOREIGN KEY (`trabajador_idTrabajador`)
    REFERENCES `nettick`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`actividad_cub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`actividad_cub` (
  `idActividad_Cub` INT NOT NULL AUTO_INCREMENT,
  `Actividad_Plantilla_idActividad` INT NOT NULL,
  `Cantidad` INT NULL,
  `tiempo_proyeccion` INT NULL,
  `tiempo_real` INT NULL,
  `descripcion` VARCHAR(500) NULL,
  `Cubicacion_idCubicacion` INT NOT NULL,
  PRIMARY KEY (`idActividad_Cub`, `Actividad_Plantilla_idActividad`, `Cubicacion_idCubicacion`),
  INDEX `fk_Actividad_Cubicacion_Actividad_Plantilla1_idx` (`Actividad_Plantilla_idActividad` ASC),
  INDEX `fk_Actividad_Cub_Cubicacion1_idx` (`Cubicacion_idCubicacion` ASC),
  CONSTRAINT `fk_Actividad_Cubicacion_Actividad_Plantilla1`
    FOREIGN KEY (`Actividad_Plantilla_idActividad`)
    REFERENCES `nettick`.`actividad_plantilla` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Cub_Cubicacion1`
    FOREIGN KEY (`Cubicacion_idCubicacion`)
    REFERENCES `nettick`.`cubicacion` (`idCubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`material_has_actividad_cub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`material_has_actividad_cub` (
  `Material_idMaterial` INT NOT NULL,
  `Actividad_Cub_idActividad_Cub` INT NOT NULL,
  `cantMaterial` INT NULL,
  `tipo` TINYINT(1) NULL,
  INDEX `fk_Material_has_Actividad_Cub_Actividad_Cub1_idx` (`Actividad_Cub_idActividad_Cub` ASC),
  INDEX `fk_Material_has_Actividad_Cub_Material1_idx` (`Material_idMaterial` ASC),
  PRIMARY KEY (`Actividad_Cub_idActividad_Cub`, `Material_idMaterial`),
  CONSTRAINT `fk_Material_has_Actividad_Cub_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `nettick`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Actividad_Cub_Actividad_Cub1`
    FOREIGN KEY (`Actividad_Cub_idActividad_Cub`)
    REFERENCES `nettick`.`actividad_cub` (`idActividad_Cub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettick`.`proveedores` (
  `idproveedores` INT NOT NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
