-- MySQL Script generated by MySQL Workbench
-- 07/21/16 11:30:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema nettick
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nettick
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `nettick`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Estado` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`solicitud` ;

CREATE TABLE IF NOT EXISTS `nettick`.`solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `fechaSolicitud` DATE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `hora_visita` DATE NULL,
  `nombre_contacto` VARCHAR(30) NOT NULL,
  `apellido_contacto` VARCHAR(30) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `telefono_contacto` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `prioridad` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitud_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_solicitud_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `nettick`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `nettick`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `prioridad` VARCHAR(45) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `fechaModificacion` VARCHAR(45) NULL,
  `piso` VARCHAR(20) NOT NULL,
  `sector` VARCHAR(30) NOT NULL,
  `solicitud_idsolicitud` INT NULL,
  `observacion` VARCHAR(400) NULL,
  `compromisos` VARCHAR(400) NULL,
  PRIMARY KEY (`idProyecto`),
  INDEX `fk_requerimiento_solicitud1_idx` (`solicitud_idsolicitud` ASC),
  CONSTRAINT `fk_requerimiento_solicitud1`
    FOREIGN KEY (`solicitud_idsolicitud`)
    REFERENCES `nettick`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Cubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Cubicacion` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Cubicacion` (
  `idCubicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `fecha_modificacion` DATE NULL,
  `fecha_envio` DATE NULL,
  `fecha_aprovacion` DATE NULL,
  `Estado_idEstado` INT NOT NULL,
  `proyecto_idProyecto` INT NOT NULL,
  PRIMARY KEY (`idCubicacion`),
  INDEX `fk_Cubicacion_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Cubicacion_proyecto1_idx` (`proyecto_idProyecto` ASC),
  CONSTRAINT `fk_Cubicacion_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `nettick`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cubicacion_proyecto1`
    FOREIGN KEY (`proyecto_idProyecto`)
    REFERENCES `nettick`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Rubro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Rubro` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Rubro` (
  `idRubro` INT NOT NULL AUTO_INCREMENT,
  `nombre_rubro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRubro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`actividad_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`actividad_categoria` ;

CREATE TABLE IF NOT EXISTS `nettick`.`actividad_categoria` (
  `idActividad_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `Rubro_idRubro` INT NOT NULL,
  PRIMARY KEY (`idActividad_categoria`),
  INDEX `fk_actividad_categoria_Rubro1_idx` (`Rubro_idRubro` ASC),
  CONSTRAINT `fk_actividad_categoria_Rubro1`
    FOREIGN KEY (`Rubro_idRubro`)
    REFERENCES `nettick`.`Rubro` (`idRubro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre_act` VARCHAR(45) NOT NULL,
  `valor` INT NULL,
  `tiempo_ejecucion` INT NULL,
  `Cubicacion_idCubicacion` INT NULL,
  `idActividad_categoria` INT NOT NULL,
  `comentario1` VARCHAR(500) NULL,
  `comentario 2` VARCHAR(500) NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Cubicacion_idx` (`Cubicacion_idCubicacion` ASC),
  INDEX `fk_Actividad_actividad_categoria1_idx` (`idActividad_categoria` ASC),
  CONSTRAINT `fk_Actividad_Cubicacion`
    FOREIGN KEY (`Cubicacion_idCubicacion`)
    REFERENCES `nettick`.`Cubicacion` (`idCubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_actividad_categoria1`
    FOREIGN KEY (`idActividad_categoria`)
    REFERENCES `nettick`.`actividad_categoria` (`idActividad_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`unidadM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`unidadM` ;

CREATE TABLE IF NOT EXISTS `nettick`.`unidadM` (
  `idunidadM` INT NOT NULL AUTO_INCREMENT,
  `nombre_unidad` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunidadM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Marca` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Material` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre_material` VARCHAR(45) NOT NULL,
  `cod_fabricante` VARCHAR(45) NOT NULL,
  `valor` INT NULL,
  `unidadM_idunidadM` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_Material_unidadM1_idx` (`unidadM_idunidadM` ASC),
  INDEX `fk_Material_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Material_unidadM1`
    FOREIGN KEY (`unidadM_idunidadM`)
    REFERENCES `nettick`.`unidadM` (`idunidadM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `nettick`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Material_has_Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Material_has_Actividad` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Material_has_Actividad` (
  `Material_idMaterial` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `cantMaterial` INT NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Material_idMaterial`, `Actividad_idActividad`),
  INDEX `fk_Material_has_Actividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  INDEX `fk_Material_has_Actividad_Material1_idx` (`Material_idMaterial` ASC),
  CONSTRAINT `fk_Material_has_Actividad_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `nettick`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Actividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `nettick`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`herramienta_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`herramienta_categoria` ;

CREATE TABLE IF NOT EXISTS `nettick`.`herramienta_categoria` (
  `idherramienta_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`idherramienta_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Herramienta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Herramienta` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Herramienta` (
  `idHerramienta` INT NOT NULL AUTO_INCREMENT,
  `nombre_herramienta` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `herramienta_categoria_idherramienta_categoria` INT NOT NULL,
  PRIMARY KEY (`idHerramienta`),
  INDEX `fk_Herramienta_herramienta_categoria1_idx` (`herramienta_categoria_idherramienta_categoria` ASC),
  CONSTRAINT `fk_Herramienta_herramienta_categoria1`
    FOREIGN KEY (`herramienta_categoria_idherramienta_categoria`)
    REFERENCES `nettick`.`herramienta_categoria` (`idherramienta_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Herramienta_has_Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Herramienta_has_Actividad` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Herramienta_has_Actividad` (
  `Herramienta_idHerramienta` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`Herramienta_idHerramienta`, `Actividad_idActividad`),
  INDEX `fk_Herramienta_has_Actividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  INDEX `fk_Herramienta_has_Actividad_Herramienta1_idx` (`Herramienta_idHerramienta` ASC),
  CONSTRAINT `fk_Herramienta_has_Actividad_Herramienta1`
    FOREIGN KEY (`Herramienta_idHerramienta`)
    REFERENCES `nettick`.`Herramienta` (`idHerramienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Herramienta_has_Actividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `nettick`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`Gama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`Gama` ;

CREATE TABLE IF NOT EXISTS `nettick`.`Gama` (
  `idGama` INT NOT NULL AUTO_INCREMENT,
  `linea_producto` VARCHAR(45) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idGama`),
  INDEX `fk_Gama_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Gama_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `nettick`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`cargo` ;

CREATE TABLE IF NOT EXISTS `nettick`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombreCargo` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `nettick`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre_trabajador` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(20) NOT NULL,
  `apellidoM` VARCHAR(20) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `observacion` VARCHAR(400) NULL,
  `cargo_idcargo` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtrabajador`),
  INDEX `fk_trabajador_cargo1_idx` (`cargo_idcargo` ASC),
  CONSTRAINT `fk_trabajador_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `nettick`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettick`.`proyecto_has_trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nettick`.`proyecto_has_trabajador` ;

CREATE TABLE IF NOT EXISTS `nettick`.`proyecto_has_trabajador` (
  `proyecto_idProyecto` INT NOT NULL,
  `trabajador_idTrabajador` INT NOT NULL,
  PRIMARY KEY (`proyecto_idProyecto`, `trabajador_idTrabajador`),
  INDEX `fk_requerimiento_has_trabajador_trabajador1_idx` (`trabajador_idTrabajador` ASC),
  INDEX `fk_requerimiento_has_trabajador_requerimiento1_idx` (`proyecto_idProyecto` ASC),
  CONSTRAINT `fk_requerimiento_has_trabajador_requerimiento1`
    FOREIGN KEY (`proyecto_idProyecto`)
    REFERENCES `nettick`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requerimiento_has_trabajador_trabajador1`
    FOREIGN KEY (`trabajador_idTrabajador`)
    REFERENCES `nettick`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


